meta:
  engine: 4.1.0
units:
  kx: cx
  ky: cy
  px: kx + 5
  py: ky + 4
points:
  zones:
    matrix:
      key.tags:
        - keys
      anchor.shift: [100, -150]
      rotate: 3
      columns:
        C1:
        C2:
          key.stagger: 3
        C3:
          key.origin: [-200, -20]
          key.splay: -3
          key.stagger: 12
        C4:
          key.stagger: 5
        C5:
          key.stagger: -6
        C6:
          key.stagger: -2
      rows:
        R1:
        R2:
        R3:
    thumbfan:
      key.tags:
        - thumb_keys
      anchor:
        ref: matrix_C6_R1
        shift: [-2*(kx+1), -ky]
      columns:
        C1:
        C2:
        C3:
          key.spread: 21.25
          key.splay: -28
          key.origin: [-11.75, -9]
        C4:
          key.spread: 21.25
          key.splay: -28
          key.origin: [-9.5, -9]
      rows:
        RT:
    mcu:
      key.tags:
        - helper
      anchor:
        - ref: matrix_C6_R3
          shift: [u/2+18/2+1.6,u/2-33/2]
    display:
      key.tags:
        - helper
      anchor:
        - ref: mcu
          shift: [0,-3.5]
    screw_hole_1:
      key.tags:
        - screw_hole
      anchor:
        aggregate.parts:
          - ref: matrix_C1_R2
          - ref: matrix_C2_R3
        shift: [0, -3]
    screw_hole_2:
      key.tags:
        - screw_hole
      anchor:
        aggregate.parts:
          - ref: matrix_C1_R1
          - ref: matrix_C2_R1
        shift: [0, -10]
    screw_hole_3:
      key.tags:
        - screw_hole
      anchor:
        aggregate.parts:
          - ref: matrix_C5_R2
          - ref: matrix_C6_R3
        shift: [0, -5]
    screw_hole_4:
      key.tags:
        - screw_hole
      anchor:
        aggregate.parts:
          - ref: matrix_C5_R1
          - ref: thumbfan_C1_RT
    screw_hole_5:
      key.tags:
        - screw_hole
      anchor:
        aggregate.parts:
          - ref: matrix_C6_R1
          - ref: thumbfan_C3_RT
        shift: [20, 0]
outlines:
  _keys:
    - what: rectangle
      where: [keys, thumb_keys]
      size: [px, py]
  _keycaps:
    - what: rectangle
      where: [keys, thumb_keys]
      size: [cx, cy]
      fillet: 3
  _thumbfan_filler:
    - what: polygon
      points:
        - ref: thumbfan_C1_RT
          shift: [-0.5px, -0.5py]
        - ref: matrix_C1_R1
          shift: [-0.5px, -0.5py]
        - ref: matrix_C1_R1
        - ref: matrix_C5_R1
        - ref: thumbfan_C3_RT
          shift: [0.5px, 0.5py]
  _mcu_filler:
    - what: polygon
      points:
        - ref: matrix_C6_R3
          shift: [0.5px, 0.5py]
        - ref: matrix_C6_R3
          shift: [30, 0.5py]
        - ref: matrix_C6_R3
          shift: [30, -4py]
        - ref: thumbfan_C4_RT
          shift: [-0.5px, -0.5py]
        - ref: thumbfan_C3_RT
          shift: [-0.5px, -0.5py]
  _board:
    - what: outline
      name: _keys
    - what: outline
      name: _thumbfan_filler
      operation: add
    - what: outline
      name: _mcu_filler
      operation: add
  _mcu:
    - what: rectangle
      where: [mcu]
      size: [17.78,33]
      fillet: 1
    - what: rectangle
      where: [mcu]
      size: [8.94,7.35]
      fillet: 0.1
      operation: stack
      adjust:
        shift: [0,33/2-7.35/2+0.7]
  _display:
    - what: rectangle
      where: [display]
      size: [14,36]
      fillet: 0.5
    - what: rectangle
      where: [display]
      size: [12.82,2.66]
      operation: stack
      fillet: 0.1
      adjust:
        shift: [0,-16.7]
    - what: rectangle
      where: [display]
      size: [10.8,24.6]
      operation: stack
      adjust:
        shift: [0,-0.75]
  _mcu_cluster:
    - what: outline
      name: _mcu
      operation: stack
    - what: outline
      name: _display
      operation: stack
  preview:
    - what: outline
      name: _keycaps
    - what: outline
      name: _board
      operation: stack
    - what: outline
      name: _mcu_cluster
      operation: stack 
pcbs:
  jade44:
    template: kicad8
    outlines.main.outline: _board
    footprints:
      matrix_keys:
        what: ceoloide/switch_choc_v1_v2
        where: [keys]
        params: &switches
          choc_v1_support: false
          include_plated_holes: false
          include_stabilizer_pad: false
          from: "{{colrow}}"
          to: "{{col.name}}"
          hotswap: true
          solder: false
          reversible: true
          switch_3dmodel_filename: '/home/jay/src/keyswitch_model/choc/v2/KiCad/lofree/wizard.step'
          switch_3dmodel_xyz_rotation: [0, 180, 0]
          switch_3dmodel_xyz_offset: [0, 0, -1.5]
          hotswap_3dmodel_filename: '/home/jay/src/keyswitch_model/socket/KiCad/choc.step'
          hotswap_3dmodel_xyz_rotation: [0, 180, 0]
          hotswap_3dmodel_xyz_offset: [0, -6, 1.5]
        adjust:
          rotate: 180
      thumb_keys:
        what: ceoloide/switch_choc_v1_v2
        where: [thumb_keys]
        params:
          <<: *switches
      diodes_for_matrix_keys:
        what: ceoloide/diode_tht_sod123
        where: [keys]
        params: &diodes
          from: "{{colrow}}"
          to: "{{row}}"
          include_tht: true
          reversible: true
        adjust:
          shift: [0, -9.5]
          rotate: 180
      diodes_for_thumb_keys:
        what: ceoloide/diode_tht_sod123
        where: [thumb_keys]
        params:
          <<: *diodes
        adjust:
          rotate: 180
          shift: [0, -8.0]
      controller:
        what: ceoloide/mcu_nice_nano
        where:
          ref: mcu
        params:
          reversible: true
          reverse_mount: true
          mcu_3dmodel_filename: '/home/jay/src/kb_ergogen_fp/3d_models/Nice_Nano_V2.step'
          # Pin names are Arduino pin names, not the MCU pin names.
          # For example, "P2" here refers to the pin labeled "D2" on the board in Arduino terms, 
          # which is P0.17 in Nice Nano V2 terms.
          P1: CS
          P2: MOSI
          P3: SCK
          # Four rows, six columns.
          P4: R3
          P5: R2
          P6: R1
          P7: RT
          P21: C1
          P20: C2
          P19: C3
          P18: C4
          P15: C5
          P14: C6
          # Unused pins.
          P0: NC
          P8: NC
          P9: NC
          P10: NC
          P16: NC
      display:
        what: ceoloide/display_nice_view
        where: display
        params:
          reversible: true
      power_switch:
        what: ceoloide/power_switch_smd_side
        where: matrix_C6_R3
        params:
          side: B
          reversible: true
        adjust:
          rotate: 90
          shift: [0, 0.5py - 2]
      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        where: mcu
        params:
          reversible: true
          side: B
        adjust:
          shift: [1.5, -35]
          rotate: -90
      reset_switch:
        what: ceoloide/reset_switch_tht_top
        where: mcu
        params:
          side: B
          reversible: true
        adjust:
          shift: [6.75,-35]
          rotate: 90
      m2_screws:
        what: ceoloide/mounting_hole_npth
        where: [screw_hole]
        params:
          hole_size: 4.6
          hole_drill: 2.2